//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVMakerBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class cv
    {
        public int ID { get; set; }
        public string Names { get; set; }
        public string Email { get; set; }
        public string Addres { get; set; }
        public string Contact { get; set; }
    }
}
